"""Deterministic mock LLM.

Emulates the two calls a real Claude client would make:

1. ``reason``        - a chain-of-thought over the change (steps, success/
                       failure scenarios, rationale).
2. ``generate_test`` - a compilable ``@SpringBootTest`` JUnit 5 class that
                       exercises those scenarios.

Everything is derived from the analyzed change so output is stable and
explainable — no randomness, no network.
"""
from __future__ import annotations

import re
from typing import List

from ..models import ChangeUnit, ReasoningTrace
from .base import LLMClient, TestGenRequest


def _camel_to_field(name: str) -> str:
    return name[0].lower() + name[1:] if name else name


def _primary_class(units: List[ChangeUnit]) -> str:
    # Prefer a service class as the unit-under-test, else the first changed class.
    for u in units:
        if "service" in u.file_path.lower():
            return u.class_name
    return units[0].class_name


class MockLLMClient(LLMClient):
    name = "mock"

    # ---- stage 1: reasoning ------------------------------------------------
    def reason(self, req: TestGenRequest) -> ReasoningTrace:
        steps: List[str] = []
        scenarios: List[str] = []

        steps.append(
            f"변경된 유닛 {len(req.units)}개를 하나의 비즈니스 흐름으로 묶어 분석한다."
        )
        for u in req.units:
            steps.append(
                f"[{u.display_name}] 의도='{u.intent}' → {u.intent_reason}"
            )
            scenarios.extend(self._scenarios_for(u))

        steps.append(
            "각 의도에 대해 정상(성공) 케이스와 예외(실패) 케이스를 최소 1개씩 도출한다."
        )
        steps.append(
            "@SpringBootTest 컨텍스트에서 대상 빈을 주입하고, 도출한 케이스를 "
            "JUnit5 assertion으로 검증하는 테스트를 작성한다."
        )

        rationale = (
            f"'{_primary_class(req.units)}'의 변경 의도("
            + ", ".join(sorted({u.intent for u in req.units}))
            + ")에 근거하여, 변경으로 새로 보장되어야 하는 동작을 성공/실패 "
            "케이스로 나누어 검증하도록 테스트를 구성함."
        )
        return ReasoningTrace(steps=steps, scenarios=scenarios, rationale=rationale)

    def _scenarios_for(self, u: ChangeUnit) -> List[str]:
        m = u.method.name if u.method else "changedBehavior"
        if u.intent == "feature":
            return [
                f"성공: {m} 이(가) 정상 입력에 대해 기대 결과를 반환한다.",
                f"실패: {m} 이(가) 잘못된 입력에 대해 예외/오류를 처리한다.",
            ]
        if u.intent == "condition":
            return [
                f"성공: 변경된 조건의 참(true) 분기가 올바르게 동작한다 ({m}).",
                f"성공: 변경된 조건의 거짓(false) 분기가 올바르게 동작한다 ({m}).",
            ]
        if u.intent == "performance":
            return [
                f"성공: {m} 이(가) 최적화 이후에도 기존과 동일한 결과를 반환한다(동치성).",
                f"성공: {m} 이(가) 반복 호출 시 예외 없이 완료된다.",
            ]
        return [
            f"성공: {m} 의 기존 계약(정상 동작)이 회귀 없이 유지된다.",
            f"실패: {m} 의 경계/예외 입력이 안전하게 처리된다.",
        ]

    # ---- stage 2: test generation -----------------------------------------
    def generate_test(self, req: TestGenRequest, reasoning: ReasoningTrace) -> str:
        pkg = req.project_package
        target = _primary_class(req.units)
        field = _camel_to_field(target)
        test_class = f"{target}GeneratedTest"

        # One @Test method per scenario, named deterministically.
        methods = []
        for i, sc in enumerate(reasoning.scenarios, start=1):
            kind = "success" if sc.startswith("성공") else "failure"
            methods.append(self._render_test_method(i, kind, sc, field, target))

        methods_src = "\n\n".join(methods)
        scenario_doc = "\n".join(f"     *   - {s}" for s in reasoning.scenarios)
        units_doc = ", ".join(u.display_name for u in req.units)

        return f"""package {pkg};

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

/**
 * AUTO-GENERATED by codetest (mock LLM backend).
 *
 * Covered change units: {units_doc}
 *
 * Reasoning (chain-of-thought) scenarios:
{scenario_doc}
 *
 * {reasoning.rationale}
 */
@SpringBootTest
class {test_class} {{

    @Autowired(required = false)
    private {target} {field};

    @Test
    @DisplayName("Spring context loads and target bean is available")
    void contextAndBeanLoads() {{
        // A generated smoke test: verifies the @SpringBootTest context wires up.
        assertNotNull({field}, "{target} bean should be injectable in the test context");
    }}

{methods_src}

    private void assumeBeanPresent() {{
        org.junit.jupiter.api.Assumptions.assumeTrue({field} != null);
    }}
}}
"""

    def _render_test_method(self, idx: int, kind: str, scenario: str,
                            field: str, target: str) -> str:
        safe = re.sub(r"[^A-Za-z0-9]", "", scenario.split(":", 1)[-1].strip().title())[:40]
        method_name = f"scenario{idx}_{kind}_{safe or 'behavior'}"
        if kind == "success":
            body = (
                f"        // {scenario}\n"
                f"        assumeBeanPresent();\n"
                f"        assertDoesNotThrow(() -> {{\n"
                f"            // TODO: invoke the changed behavior on `{field}` and\n"
                f"            //       assert the expected result for this scenario.\n"
                f"        }});"
            )
        else:
            body = (
                f"        // {scenario}\n"
                f"        assumeBeanPresent();\n"
                f"        // TODO: drive the failure path and assert the thrown exception,\n"
                f"        //       e.g. assertThrows(IllegalArgumentException.class, () -> ...);\n"
                f"        assertTrue(true, \"failure-path placeholder for: {scenario}\");"
            )
        display = scenario.replace('"', "'")
        return (
            f"    @Test\n"
            f'    @DisplayName("{display}")\n'
            f"    void {method_name}() {{\n"
            f"{body}\n"
            f"    }}"
        )
